### ISSUE TITLE
请求授权添加至整合包

### ISSUE THREAD

**Issue by Chikage0o0** [Snownee/JadeAddonsFabric#1]
### Minecraft version

1.18.2

### Mod version

1.0.0

### Modloader version

10

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

你好，我想在我的整合包内添加你的模组JadeAddon，可以吗？
https://github.com/Chikage0o0/CreateOrigin

非常抱歉，我找不到别的方式与你进行沟通，我尝试了发送邮件至i@snownee.com 但是发送失败了

**Comment by Snownee** [comment]
在CurseForge发布的整合包无需授权

**Comment by Chikage0o0** [comment]
modrinth发布的整合包需要授权
或者大佬在modrinth传一份也行

**Comment by Snownee** [comment]
I authorize CreateOrigin modpack to include Jade Addons on Modrinth
