### ISSUE TITLE
Create and Jade Additions Bug

### ISSUE THREAD

**Issue by HypedCritic** [Snownee/JadeAddonsFabric#10]
### Minecraft version

1.19.2

### Mod version

3.2.0

### Modloader version

Fabric 0.14.21

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

Create Mod crashes with Jade Additions 

### Issue description

On startup, it will take less than even a few minutes for the game to crash and bring it back to the launcher, describing it as a "ponder" issue. 
[crash-2023-06-20_09.36.16-client.txt](https://github.com/Snownee/JadeAddonsFabric/files/11802211/crash-2023-06-20_09.36.16-client.txt)

**Comment by Snownee** [comment]
update Create
