### ISSUE TITLE
Create: Can't ponder (Fabric)

### ISSUE THREAD

**Issue by MrGreenTea** [Snownee/JadeAddonsFabric#11]
### Minecraft version

1.20.1

### Mod version

5.2.1

### Modloader version

Fabric: Loader 0.14.23 + API 0.90.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://mclo.gs/OT7GyYf

### Issue description

# Summary

When using Jade Addons and Create 0.5.1 together, I can't ponder from the inventories:

# Screenshots

## Expected
![image](https://github.com/Snownee/JadeAddonsFabric/assets/9407731/f738f3ab-86f6-428f-9a0a-3b656c7e8ae8)

## Actual
![image](https://github.com/Snownee/JadeAddonsFabric/assets/9407731/c0333efa-c33b-4c0a-9ce2-ee94a583fb7e)

# Mods

I've created a modrinth modpack that reproduces it for me: [Create + Jade _ Ponder Bug Repro 1.0.0.mrpack.zip](https://github.com/Snownee/JadeAddonsFabric/files/12844019/Create.%2B.Jade._.Ponder.Bug.Repro.1.0.0.mrpack.zip)

It's pretty consistent, but just when I tried to create the screenshot for you it looked all fine. After restarting minecraft I got it reproduced again though.

## Mod versions

- Create Fabric  | `0.5.1-d-build.1161+mc1.20.1`
- Fabric API | `0.90.0+1.20.1`
- Jade Addons (Fabric) | `5.2.1`
- Jade | `11.6.1`

**Comment by liamwerk7676** [comment]
oh nice thanks for lettin me know buddy

**Comment by Snownee** [comment]
Please update Jade
