### ISSUE TITLE
Modpacks?

### ISSUE THREAD

**Issue by lexi-the-cute** [Snownee/JadeAddonsFabric#13]
### Minecraft version

*

### Mod version

*

### Modloader version

Fabric

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Can you write down if modpacks are allowed and/or provide a license file? https://choosealicense.com/

**Comment by Snownee** [comment]
Hi.

You are allowed to add this mod to your modpack, as long as the modpack is only published on CurseForge or Modrinth.
