### ISSUE TITLE
[Suggestion] Show Tooltip For Items On Create Belt

### ISSUE THREAD

**Issue by ChloeDawn** [Snownee/JadeAddonsFabric#14]
### Minecraft version

1.20.1

### Mod version

5.2.2

### Modloader version

47.1.100

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

It would be nice if there was an option to show tooltips for items on Create belts, as opposed to just reporting the belt itself. It could also respect the "Item Description" option that regular item entities have as well.

**Comment by Snownee** [comment]
Thanks for the suggestion. We have no plans for this at this time.
