### ISSUE TITLE
No energy is displayed in the machines and cables of the Modern industrialization mod 

### ISSUE THREAD

**Issue by Kisuny** [Snownee/JadeAddonsFabric#18]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

3.2.0

### Modloader version

0.15.11

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

The mod installation site says that the jade addon supports displaying energy information in Modern industrialization mod cables, but it doesn't.

![image](https://github.com/user-attachments/assets/e60b0095-f689-49b1-8422-2fed0049bfd6)
![image](https://github.com/user-attachments/assets/bb1c1a87-0c0b-45cf-9229-580136b92992)

**Comment by Snownee** [comment]
I no longer maintain 1.19.2. But it should have support for Modern Industrialization 1.6.9
