### ISSUE TITLE
Problem with deleted optional dependency (Secret Rooms, project-359248)

### ISSUE THREAD

**Issue by itssimple** [Snownee/JadeAddonsFabric#2]
### Minecraft version

1.18.2

### Mod version

2.0.0

### Modloader version

Fabric 0.14.9

### Modpack info

https://www.curseforge.com/minecraft/modpacks/endernet-pl

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

The 8th September, 22:51 UTC, the project Secret Rooms (project-359248) was deleted/removed from CurseForge, making installation of dependencies fail (even if it's marked as optional).

**Comment by Snownee** [comment]
thanks for reporting
